### ISSUE TITLE
When user deletes a verified api key from their GW2 account, the verify remains

### ISSUE THREAD

**Issue by noskillahh** [siemandelc/VerifyBot#15]
Hi, I love the bot. Im not a coder at all; but it seems that if a verified user deletes their verified API key from their GW2 account, the reverifyservice throws an exception but doesnt actually unverify the user. Im not sure how to approach this.

**Comment by siemandelc** [comment]
I've noticed sometimes API calls just do not work. I think I coded it this way back in the day because I didn't want it to nuke a database if everything blew up. I'll have to look into if they return a "key deleted" code or not. (I don't know enough about the GW2 API to know if it does this already)

**Comment by noskillahh** [comment]
I figured this was the reason why. Right now (and again, Im definitely not a coder) it looks like any exception will just throw stop the reverification process and it tries again two more times. But a wrong api key seems to have a very specific response though:
https://api.guildwars2.com/v2/account?access_token=312BE86C-291B-2C46-90AF-C1428BE9237B411F18F2-92F3-4B7A-971C-111111111111

I dont know how the api framework works code wise so I only see the json response on the gw2 site really, but from what I understand youre just kind of comparing strings that the api prints right? Is there any way to specifically check for the "invalid key" response? I found some relation to the invalid key thing in the code but it seems thats just you checking if its the correct length.

**Comment by siemandelc** [comment]
It should return the same JSON, I'll investigate when I get time and see if I can get this fixed for you.

**Comment by noskillahh** [comment]
Thanks, Ill try some stuff myself, not in a hurry really.

**Comment by siemandelc** [comment]
Fixed in  5592166
