### ISSUE TITLE
Need a way to reuse an API key

### ISSUE THREAD

**Issue by thajcak** [siemandelc/VerifyBot#5]
For whatever reason, people are either losing their verified status or have set up a second account to use in Discord. In these cases, they're no longer able to use the verify bot because it believes they're already set up.

> Starting Verification Process...
> Account is already verified. If you are having issues message a verifer

We need some kind of system in place that either
1. Allows for the API key to be used across multiple accounts (this _could_ lead to key sharing).
2. Associates the API key to the new account and removes it from the previous.

Either way, this situation requires manual verification which then doesn't exist in the database and could be revoked in the future during a purge.

**Comment by siemandelc** [comment]
https://github.com/siemandelc/VerifyBot/commit/9eb6988f726f283e5a03ae08e354cb149d663e1f
